# Generated by Django 4.0.6 on 2022-07-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateTimeField()),
            ],
        ),
    ]
