# Generated by Django 4.0.6 on 2022-07-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiares',
            new_name='Pariente',
        ),
    ]
