# Generated by Django 4.0.6 on 2022-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0002_rename_familiares_pariente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pariente',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
